### ISSUE TITLE
Timeline feature

### ISSUE THREAD

**Issue by aFarkas** [Popmotion/popmotion#102]
thanks for this project. Is there a timeline plugin to control multiple animations?

**Comment by InventingWithMonster** [comment]
Not yet.

There is a sequencer in the works (released some time this week) that will control and sequence multiple Actors. This will provide many of the benefits of a timeline. But it won't be a timeline in the traditional GreenSock sense because of our support for physics and user input. It will be more like a linear sequence of triggers. 

This is inline with our focus on user interface interactions over larger animations.

I'll let you know when it's released as part of 3.4.0.
