### ISSUE TITLE
Is it possible to force css role to svg element?

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#106]
Hi Matt @InventingWithMonster , I have this codepen http://codepen.io/tinchox5/pen/WQZLQG in which I try to use the css benefits in order to override some svg limitations (ej rotateX, rotateY). I tried to force css role when I set Actor,but that didn't work. So, I wrote some css rules using onComplete but this is not the idea. I mean it would be nice to set css values directly in Tween.
Have you got any suggestion?
Thanks

**Comment by InventingWithMonster** [comment]
Hey Juan

What problems are you running into with `rotateX` and `rotateY`? Could you show me an idealised version of what you're trying to accomplish? It doesn't need to work, I just need to understand what you're trying to do and see if it's something I can fix in Popmotion or if not there's another way of accomplishing it.

You can, however, force the CSS role and you were doing it correctly, based on the comment. But I wouldn't expect it to work in this instance as DOM and SVG translations work quite differently and Popmotion tries to resolve those differences.

To set transforms on a SVG you can't use CSS syntax in most instances - https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

So, solutions:

1) Create an element-less Actor. It will assign no role and you can animate all values as you see fit. Then, in an `onUpdate` event, you can assign the `transform` property yourself with an attribute you build up (like you have in `onComplete`) - you can use ui.attr.set() to accomplish this, because it should be set to the `transform` attribute, not the `style` attribute (like you would with CSS). Depending on what you're trying to do with `rotate` this might not work (because of 3D SVG transforms), in which case:

2) Create a second Actor, this time for the SVG element. The SVG is rendered in DOM and you can apply CSS transforms on it. It might get detected as an SVG element, which might be a bug I need to fix. In which case I'd force CSS role on this Actor like you were before. Now this Actor can handle rotation, and everything else can be done on the `path` actor.

Please let me know how you get on!

**Comment by tinchox5** [comment]
Hey Matt, I'll try to explain my idealized version: "I want to apply
rotateX and rotateY directly into Tween affecting an SVG element". That is
not possible as you said before because, in most instance, you can't use
CSS syntax to set transforms on a SVG and SVG doesn't support rotateX or
rotateY, just rotate.

I know that, but, on the other hand, you can apply CSS transforms on SVG
that is rendered in DOM (as I did in onComplete). So, my ideal solution is
that Popmotion would be able to handle a MIX of SVG and CSS roles in the
same Tween or Simulate. Something like this:

var myAction = new ui.Tween({
       duration: 1000,
       ease: 'backOut',
       values: {

         // automatic detected role, in this case: svg
          scale:{current: 0, to: 3},
          stroke: "#0099ff",
          width:2,
          opacity: {current:0, to: 1},
         // Proposal: force Tween to use css role
         // that would be the "same" to write :
         //  $actor.css('transform','rotateX(25deg) rotateY(25deg)');
           use ui.css: {
             rotateX: 25,
             rotateY: 25
           }
        }
});

Regretfully, one thing is to propose something like that, and another
totally different is to implement it.  What do you think?

**Comment by InventingWithMonster** [comment]
Sorry for the delayed reply! 

It looks like forcing the `cont` with `as: ui.css` on your latest example does work (to a degree). I think part of the problem is some browsers don't support CSS on SVG which is why we don't do it.

I'm going to release an fix in about ten minutes (3.4.2) which should mean you don't have to force the css role `svg` tags.

**Comment by InventingWithMonster** [comment]
@tinchox5 version 3.4.2 released

**Comment by tinchox5** [comment]
Thank you!
​
