### ISSUE TITLE
Website and pricing questions

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#119]
Hi Matt, I'm bit confused. I know for twitter that popmotion 4 has already released, but in the website an older version is shown.  Another thing that confused me is what happened with the price of popmotion. Is it free or not? is there a way to donate in order to support the development?
Thank you,
Martin

**Comment by InventingWithMonster** [comment]
Hey Martin,

Sorry about the confusion(s)! The version on the website is updated by me, manually, so its often at risk of falling out of sync and usually does. I'd say https://github.com/Popmotion/popmotion/releases is your best bet here but I'll do my best to remember.

The price of Popmotion, well this is something I'm currently debating myself about. I need to figure out a way to support it, ultimately, because supporting it in my free time isn't a long-term proposition.

It will always be free for personal and non-profit, that's an absolute must for me. I played around with a commercial licence model and I'll probably settle on a one-off per-project model, I don't really enjoy the commercial stuff though which is why I took it down for a while. There's also the possibility of a Patreon-esque model for people who just wish to donate.

Do you have any opinions on the matter? I'd be interested in hearing your thoughts as probably the longest-standing user!

Thanks
Matt

**Comment by tinchox5** [comment]
Matt, I think that a commercial license model could be a right solution.
However, I was thinking in another alternative that maybe (or maybe not)
could be implemented as a complement. The idea is the implementation of a
private crowdfunding campaign in your site... in order to unlock some
future features, milestones or improvements... There are some successful
cases related to software. Maybe it is better than runs a public campaign
on kickstarter...
Also, I think that some marketing has to be done previously.
You can also contact me via email if you want.
Thank you,
Martin

2015-12-01 11:41 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by MichaelFBA** [comment]
You have probably seen this license model. 
http://packery.metafizzy.co/license.html

Might be an option for you

**Comment by InventingWithMonster** [comment]
@MichaelFBA I forgot to say last night but that really is exactly what I'm looking for, ensures protected open source use too - nice!

**Comment by MichaelFBA** [comment]
:+1:

**Comment by InventingWithMonster** [comment]
@tinchox5 As per the Packery (and I've since learned MySQL) example, via @MichaelFBA, the terms are up at https://popmotion.io/pricing

So there's a GPLv3 to safeguard open source use, and a Pro license for unrestricted use. The Pro license is a per-developer, one-off fee that gives free major version upgrades for a year (and then continuing minor version updates from then on)

And I'm sticking to this one!

@MichaelFBA just a side note I haven't forgotten about the collision detection but finding time for it has been a difficulty. I had to reimplement the core Popmotion render loop first ([explanation](popmotion.io/blog/4.0.0-released-explaining-the-new-render-loop)) but now I've made the first commits to the plugin. I'm going to start with axis-locked rectangles for DOM first, and then introduce circles and non-axis locked rectangles.
