### ISSUE TITLE
Simulate transform 

### ISSUE THREAD

**Issue by MichaelFBA** [Popmotion/popmotion#120]
Hi, hope you dont mind me asking here.

I am trying to simulate the transform: scale from 0 to 1 with a spring movement.
Similar to this: 
http://codepen.io/popmotion/pen/dogNpp

Here is a pen showing you the version i have modified.
http://codepen.io/anon/pen/VeZvqR

Unfortunately the results are somewhat different each turn. 
Is there a way to apply a duration to simulate?

Awesome library by the way. (Will definitely buy when you have collision detection) :)

**Comment by InventingWithMonster** [comment]
Try adjusting the stopSpeed property, ie: http://codepen.io/popmotion/pen/XXrXvL?editors=011

To decide when to stop a simulation it detects speed and automatically stops after x number of frames under that speed. Setting the `stopSpeed` property overrides this speed - I've set it to `0` in that example but you could play with speeds like 0.0001. 

I'll look into changing it on our end because its too low for properties like `scale` and `opacity`. I'll also look into enabling `duration` for all actions.

**Comment by MichaelFBA** [comment]
Thanks. That did the trick.
