### ISSUE TITLE
Question: moving multiple actors/tweens of non-DOM objects, in parallel?

### ISSUE THREAD

**Issue by SangSatori** [Popmotion/popmotion#136]
I'm just started using Popmotion's tweening with Three.js meshes, and am experiencing results not as expected - here's an excerpt from my code:

```javascript
for (let i = 0; i <= count; i++) {
  let snowflake = new THREE.Mesh(this.geometry, this.material);
  // set initian position
  snowflake.translateX(Math.random() * this.size);
  snowflake.translateZ(Math.random() * this.size);
  // make boundary size usable
  let size = this.size;
  new ui.Actor({
    element: snowflake,
    onUpdate: function(output) {
      snowflake.position.y = 0 - output.y;
    }
  }).start(new ui.Tween({
    loop: true,
    ease: "linear",
    dilate: Math.random(),
    values: {
      y: {
        to: size,
        from: 0
      }
    }
  }));
  this.group.add(snowflake);
};
```

What happens is that out of 10 test snowflakes, only one gets tweened - others are not affected despite initializing X number of actors with X number of tweens. I looked at #99 but I'm not sure how to circumvent this behavior. Is there anything I can do to make all objects be tweened in parallel?

**Comment by InventingWithMonster** [comment]
Nice use of dilate! I like it.

Do you have a CodePen I could prod at?

At first glance I can't see anything immediately obvious. You can set `y` like this:

```
y: size
```

As it will infer `0` as an initial value if it doesn't already exist. Also to hard-set a start value you should use `current` instead of `from`.

Is the snowflake that gets updated the final snowflake? It shouldn't be a problem but I sometimes find that behaviour when I set functions within loops - that it takes the final `snowflake` rather than binding each `function` definition to each `snowflake`. As a start could you try this:

```javascript
function setSnowflakePosition({ y }, actor) {
    actor.element.position.y = 0 - y;
}

for (let i = 0; i <= count; i++) {
  let snowflake = new THREE.Mesh(this.geometry, this.material);

  // set initian position
  snowflake.translateX(Math.random() * this.size);
  snowflake.translateZ(Math.random() * this.size);

  // make boundary size usable
  let size = this.size;

  new ui.Actor({
    element: snowflake,
    onUpdate: setSnowflakePosition
  }).start(new ui.Tween({
    loop: true,
    ease: "linear",
    dilate: Math.random(),
    values: {
        y: size
    }
  }));

  this.group.add(snowflake);
};
```

**Comment by SangSatori** [comment]
Yes! Indeed, it's the final snowflake that is the only affected. Your code does _exactly_ what I've been aiming for, right off the bat with no modification required -- thanks a lot for clearing that up! :smile:

**Comment by InventingWithMonster** [comment]
@SangSatori No worries - I've just remembered why this is happening too (if you're interested!).

As you're using a block-scoped `let` I assume you know about variable hoisting and the differences in scope between `let` and `var`. So in theory your code there should work, but I assume your transpiler (probably Babel) is simply changing `let` to `var` which is function-scoped and hoisted.

So in reality your code probably looked something like this:

```javascript
var snowflake;

for (let i = 0; i <= count; i++) {
    snowflake = new THREE.Mesh(this.geometry, this.material);

    // etc
}
```

Every time the loop runs it's changing what `snowflake` represents, but the `function`s are simply being told to look at `snowflake` rather than the actual `THREE.Mesh` instances that it temporarily represents. So by the end, all the generated `Actor`s are looking at the same `snowflake` variable and thus the last `THREE.Mesh` to be set to it and that's specifically why only one of them was moving.

Hope that helped explain this!

**Comment by SangSatori** [comment]
@InventingWithMonster Thanks a lot, this is really appreciated! I was wondering why it's like this.

Great work on the library too; it's a joy to use :smile:

**Comment by Mimi2k15** [comment]
AWESOME THANKS! !!
