### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by vkammerer** [Popmotion/popmotion#138]
Hello,

First of all, thank you a lot for the great lib. I have been looking for a long time for an open source replacement for GSAP, and I really appreciate the central place you've given to the physics engine.

I have just been looking at the source code and I was wondering why certain parts are written in ES5, while others are written in ES2015?

Moreover, as your codebase grows, and as new contributors might submit PRs, it seems necessary to ensure coding conventions are respected. Adding ESLint to the project would help a lot with that, don't you think?

If you are interested, I could help with transitioning your codebase to ES2015, and with setting ESLint rules to make sure the code is consistent across its different modules.

**Comment by InventingWithMonster** [comment]
Hey Vincent

Thanks for checking this out. I totally agree. I was hesitant to bring in
es6 because of transpilation overhead. Then, when I did, I ended up with a
hybrid using the features that impacted the size of the code base least.

If you take a look at the 'modular' branch you'll see there's a massive es6
rewrite happening. I'm playing around with the API at the moment so things
are in flux but it should give you an idea of the direction and style it's
heading in - and we do now have full linting which we'd previously turned
off because I couldn't get jslint to work nice with es6. Now it uses eslint
and Babel as the interpreter

Thanks
Matt
