### ISSUE TITLE
How to use Popmotion with NPM depency?

### ISSUE THREAD

**Issue by flayks** [Popmotion/popmotion#166]
While I used Popmotion ^4.3.4, I just installed it as a dependency in my `package.json`. But with the latest version (5+), there is no dist files. How can I manage this to easily get Popmotion updated via NPM?
Thanks 👍

**Comment by PierBover** [comment]
Are you using webpack, babel, etc?

**Comment by flayks** [comment]
Just the NPM repo! In previous versions there was minified and raw dist js files, now it's over… don't understand why.
— https://www.npmjs.com/package/popmotion

**Comment by PierBover** [comment]
Because NPM is for Node modules which are used with some module bundler like webpack, browserify, etc.

If you want to keep an updated local copy of the repo you can simply clone it, or include it as a git submodule in your repo. Although the preferred approach these days is to use NPM and a module bundler.
