### ISSUE TITLE
Firefox not working at all with v3.5.0 or v4.3.4?

### ISSUE THREAD

**Issue by cameronwh** [Popmotion/popmotion#179]
Hi guys,

We are using version 3.5.0 on our site, to animate a spinning tick icon. Identical to this one: http://codepen.io/popmotion/pen/gamwav

I have tried updating this codepen to use the latest version offered in your /assets/js directory, which is 4.3.4 however it still seems to not be working. I am unsure of what the issue is, as Firefox is just reporting an NS_ERROR_FAILURE, which I believe is a generic error. It works perfectly in Edge & Chrome, so I am a little lost.

Any ideas?

**Comment by InventingWithMonster** [comment]
Hi @cameronwh 

Sorry for the delayed reply, I've been on holiday the last couple of weeks. The latest version is `6.3.5`, though there have been substantial API changes since `4.x`. The NS_ERROR_FAILURE can occur in Firefox if the code is executed before the SVG element has been successfully appended to the DOM (solved with a 'window.ready' event), if it's a mask, or if it's otherwise invisible:

https://www.google.co.uk/search?q=ns_error_failure+svg+firefox&rlz=1C5CHFA_enGB693GB695&oq=ns_error_failure+svg+firefox&aqs=chrome..69i57.8044j0j4&sourceid=chrome&ie=UTF-8

This has been a long-standing limitation with Firefox and SVGs sadly

**Comment by cameronwh** [comment]
Hi @InventingWithMonster thanks for the reply. 

I didn't know about the NS_ERROR_FAILURE - cheers for the heads up. I'll close this now as it's not related to popmotion.
