### ISSUE TITLE
possible to animate multiple values within a react `TransitionGroup`?

### ISSUE THREAD

**Issue by chrisdrackett** [Popmotion/popmotion#192]
Say I want to animate both opacity and scale, is this currently possible?

**Comment by InventingWithMonster** [comment]
Yeah, there's a couple ways you could go about this.

1) If you want independent control over both values, you can set your values to be a [Composite](https://popmotion.io/api/composite/) of named [Value](https://popmotion.io/api/value/)s by passing an object instead of a number:

```javascript
<MotionValue v={{ opacity: 0, scale: 1 }}>
  {({opacity, scale}) => }
</MotionValue>
```

Then in you state change handlers you can animate these separately.

2) Alternatively if you want to control the two together, you can create functions with the `interpolate` [transformer](https://popmotion.io/api/transformers/) that map from one to the other:

```javascript
import { transform } from 'popmotion';
const { interpolate } = transform;

const opacityToScale = interpolate([0, 1], [0.5, 1]);

<MotionValue v={0}>
  {(opacity) => (
    <div style={{opacity, scale: opacityToScale(opacity) }}></div>
  )}
</MotionValue>
```
