### ISSUE TITLE
Composite Output to Multiple Events

### ISSUE THREAD

**Issue by jacobp100** [Popmotion/popmotion#203]
Currently `composite` only takes a single function for its `output`/`onUpdate`. What if we could give an object? That way we could avoid `trackOffset` for some use cases.

```js
const x = value(...)
const y = value(...)
pointer(e).output({ x, y })
```

**Comment by InventingWithMonster** [comment]
The reason we use trackOffset on pointer is to convert the absolute clientX values it uses to motion relative to the providing values. So clientX might be 700, but our x might be 5. If we move right 10 pixels we use trackOffset to output 15 rather than 710. 

I think providing an object is a pretty good idea in general but I wonder if providing values instead of functions was ever a good api choice. I'll have a think about this.

**Comment by jacobp100** [comment]
What would be the use case for passing in functions?

**Comment by InventingWithMonster** [comment]
I've found in my experience a lot of people only use functions. It means you avoid having to make a `value` for every `css` or `svg` property you want to set. On the other hand it means Popmotion can't handle action management for you because there's no visibility into what that function does. It's probably the core point of confusion for me writing it and when I come to explain it.

**Comment by jacobp100** [comment]
Just playing around with this. What about something like this for `value`?

```js
const onlyListenToLastAction = callback => ({
  action: null,
  setAction(action) {
    this.stop()
    this.action = action
    action.pipe(callback)
  },
  setValue(value) {
    this.stop()
    callback(value)
  },
  stop() {
    if (this.action) this.action.unpipe(callback)
    this.action = null
  },
})

const x = onlyListenToLastAction(x => renderer.set('x'))
x.setAction(spring({ ... }).start())
```
