### ISSUE TITLE
Delay used into parallel action, sync problem

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#216]
Look at this example.
I have two actions run in parallel.
The first created by chain delay and tween.
And the second one with tween.

https://codepen.io/gaougalos/pen/aVPVdG

**Comment by InventingWithMonster** [comment]
Hey man

This is because `parallel` works like RxJS's `combineLatest`, in that it doesn't emit until all actions have emitted at least once.

I'll update the docs to make sure its clear that this is the behaviour. I think it should remain like this though, as there's no other way to know what to output.

You could make an action called `just` that works like this:

```javascript
const { action } = window.popmotion;

const just = (val) => action(({ update, complete }) => {
   update(val);
   complete();
});
```

And replace your chain with:

```javascript
chain(
  just({ y: 0 }),
  delay(1000),
  tween(...)
)
```

**Comment by InventingWithMonster** [comment]
@gaou-piou Do you think it'd make more sense to output `undefined` for actions that haven't fired to give us the opportunity to provide default values?
