### ISSUE TITLE
Add `window.popmotion` to website so people can use it in their console

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#236]

**Comment by Martin-Pitt** [comment]
Just for context to others, this is because quite a few libraries out there do a bit of dogfooding for users by allowing them to toy or quickly do something with a library on their own website or documentation pages.


This is because people love to check if something is possible without having to spin up a sandbox or their development environment (or if they don't want to mess with it), by just opening up devtools and then immediately writing something and getting feedback to it.


I'd actually done this myself on the momentjs documentations a lot in the past and then found myself wanting to do on the popmotion docs as well out of habit. So was surprised I couldn't do that.


I remember conversations in the past that I wasn't the only one to do this either, so have been trying to encourage more authors of libraries to do the same as well to their websites and documentation.


Avoid the temptation to minify the source on your website so that they can see the symbols and logic when debugging as well. You should be encouraging a developer friendly approach, which ought to be obvious, but alas.


Additional bonus points if it's mentioned that you can mess with it in devtools and a single a `console.log("Feel free to experiment, the library is on window.foo")` that hints the global object available to them.

**Comment by InventingWithMonster** [comment]
It's still minified but I've just put this capability live, thanks!
