### ISSUE TITLE
PoseGroup with "singleChildOnly" feature request

### ISSUE THREAD

**Issue by anthonysapp** [Popmotion/popmotion#286]
Not sure how hard this would be to implement, but it'd be sweet if, when the _singleChildOnly_ prop is true, there was a setting to only trigger the "enter" pose of the incoming child upon completion of the "exit" pose of the outgoing child.

**Comment by dbalatero** [comment]
@InventingWithMonster you should remove this from the codebase, as your community chat + the existence of the prop implied it was a thing, and I burned time trying to figure out why it wasn't working, and ultimately I had to dive into the source to figure out it was dead code.

As an aside, I really want to be able to accomplish what this prop hints at which is animating one thing out, then animating the next thing in. Not sure how to achieve this effectively?

**Comment by dbalatero** [comment]
> As an aside, I really want to be able to accomplish what this prop hints at which is animating one thing out, then animating the next thing in. Not sure how to achieve this effectively?

I actually figured this out. The issue was that the component that I was nesting inside my `posed.div` was pulling a `currentPanel` value from Redux internally using `connect(mapStateToProps)`. When I would switch panels, the panel animating out would switch to the new panel's text, as it would internally pull a new `currentPanel` value from Redux.

The fix was to pass that down from outside the individual component, so I ended up with:

```es6
import { getCurrentPanel } from 'path/to/selectors'

const PosedPanel = posed.div({
  enter: {
    opacity: 1,
    delay: 400,
    transition: tween({ duration: 400 })
  },
  exit: {
    opacity: 0,
    transition: tween({ duration: 400 })
  }
})

const App = ({ currentPanel }) => (
  <PoseGroup>
    <PosedPanel key={`panel-${currentPanel.name}`}>
      <Panel panel={currentPanel} />
    </PosedPanel>
  </PoseGroup>
)

function mapStateToProps(state) {
  return {
    currentPanel: getCurrentPanel(state)
  }
}

const ConnectedApp = connect(mapStateToProps)(App)

ReactDOM.render(<ConnectedApp />, document.getElementById('react-root'))
```
