### ISSUE TITLE
Nested React Posegroup breaks and leaves ghost items

### ISSUE THREAD

**Issue by ConneXNL** [Popmotion/popmotion#302]
Prepared the following codepen to show the problem:
https://codepen.io/connexnl/pen/odgdXb

First click the following buttons any time you want and see how everything works beautifully.
```
Shuffle items
Add/Remove items
Shuffle + Add/Remove items
```

Now click `Shuffle Lists` and notice how the example breaks when you click any of the previous buttons.

Basically, as soon as the parent Posegroup performs any animation, future child Posegroups animations break.

**Comment by InventingWithMonster** [comment]
Thanks for the thorough codepen example! I noticed if you shuffle enough after it goes back to normal, I think? Odd. I'll have to look over it the weekend. If you add ` withParent={false}` to `ItemComponent` it seems to work a little normaller.

**Comment by ConneXNL** [comment]
@InventingWithMonster  I tried the withParent and it indeed removes some issues with what is visible.

However, it seems that a lot of zombie elements remain in the HTML.

**Comment by Andarist** [comment]
@ConneXNL which version of react-pose have you tested?

**Comment by ConneXNL** [comment]
"popmotion": "^8.4.0",
    "popmotion-pose": "^3.3.1",

**Comment by Andarist** [comment]
Thanks for the info.

I've copied your code to codesandbox - https://codesandbox.io/s/nwko4j9jpl . As I prefer it over the codepen, but also because the codepen was somehow misconfigured (at least for me). It has used global references which were missing etc.

I hope to play around with this example later to pin point the problem.

**Comment by Andarist** [comment]
I've distilled the sandbox and got less moving parts, to it became easier to debug this. Available here - https://codesandbox.io/s/0np0484nw

And I got quite to the root of the problem. It's caused by this logic here: 
https://github.com/Popmotion/popmotion/blob/82b5620cc01349ab0c093175f257b6e47e8e0cd2/packages/react-pose/src/components/Transition/children.ts#L86-L90

When we shuffle the lists (outer PoseGroup) the pose is set to `['enter', 'flip']` - later when we do whatever else (i.e. changing children of nested PoseGroup) the outer PoseGroup transitions from this `['enter', 'flip']` to `'enter'` pose (triggering the pose change as they are not equal) and that propagates to its children, they enter, even though i.e. we've just removed them. This flows through the tree and breaks stuff.

cc @InventingWithMonster

**Comment by InventingWithMonster** [comment]
I feel like if there was a way to set a custom name for the special flip
pose in `react-pose` the same way you can set custom enter and exit poses
that'd go some way to fixing this.

**Comment by Andarist** [comment]
Hm, i dont see how naming the flip pose differently would help with this. From what ive debugged the issue is caused by the fact that when we move items they are given [enter,flip] pose but later when we rerender the same items stay in place and are given enter pose which triggers setPose calls because its recognized as a change

**Comment by Andarist** [comment]
@InventingWithMonster any comments on this? I could maybe work on fixing the issue, but needs some guidance.

**Comment by InventingWithMonster** [comment]
I think I’d have to take a crack on this one myself when I get a free
moment as not too sure to be honest

**Comment by JarolinVargas** [comment]
Any update on this? I think I encountered this same issue. Having pose animation component inside parent component that also uses pose animation breaks the child component.

**Comment by mlinnem** [comment]
Also experiencing this issue.

**Comment by niekert** [comment]
For what it's worth I've started experiencing this issue after upgrading from `react-pose@3.3.7` to `react-pose@4.0.7`. I'll try and create an isolated example which shows the issue between the 2 versions but I'm struggling to reproduce in an isolated environment.

**Comment by davidohlin** [comment]
Having the same issue

**Comment by designbyadrian** [comment]
I also downgraded to 4.0.3 which solved my issue.
