### ISSUE TITLE
Popmotion pose holds on to and animates orphan DOM elements

### ISSUE THREAD

**Issue by aholachek** [Popmotion/popmotion#318]
Hi, I used react-pose for [an animation demo](https://alex.holachek.com/react-animation-comparison/?selectedKind=Animation%20Examples&selectedStory=Popmotion%20Pose&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and came across these problems:

1) Shuffling children leads to an out-of-order staggered exit transition for children
2) Specifying a "preEnterPose" removes the children's staggered enter animations completely.
3) The "preEnterPose" is only active the first time the parent element is animated in.
2) Most seriously, when re-animating the parent element in, DOM elements that do not correspond to anything in the props array are animated in (there should only be 8 cards in this image): 
<img width="638" alt="screen shot 2018-05-04 at 8 24 43 am" src="https://user-images.githubusercontent.com/3680488/39627675-a8dee29c-4f74-11e8-8912-ffb045b95cff.png">

You should be able to reproduce by checking out the demo posted above, and [my code is here](https://github.com/aholachek/react-animation-comparison/blob/master/src/popmotion-pose-example.js)

In case it's helpful, [an example demonstrating expected behavior is here](https://alex.holachek.com/react-animation-comparison/?selectedKind=Animation%20Examples&selectedStory=React-Transition-Group%20%2B%20animejs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Hopefully these issues are a result of my own user error, if so, sorry for making an issue!

**Comment by InventingWithMonster** [comment]
Thanks for the detailed explanation and code example! 

1. Know what's the cause and made a ticket here: https://github.com/Popmotion/popmotion/issues/319
2. Did you try setting a state on the children items with the same "preEnterPose"?
3. I think this is by design? It's like `ReactTransitionGroup`'s `appear` state - a way of setting an animation when the PoseGroup first appears rather than subsequent entries. Could probbly communicate this better, unless you mean something else.
4. I've been unable to replicate this state, exactly how did you do it?

**Comment by aholachek** [comment]
2. I added a `preEnterPose` to the child `PoseGroup` and it is working exactly as expected. I guess I thought in this case the children would default to using the `exit` pose to preload values if no `preEnterPose` was specified.
3. You're right, it's totally working correctly.

Thanks for making this library, btw, it's really cool how it's both powerful and user-friendly.
