### ISSUE TITLE
Old DOM items are kept in PoseGroup

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#320]
https://alex.holachek.com/react-animation-comparison/?selectedKind=Animation%20Examples&selectedStory=Popmotion%20Pose&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

1. Add new items to group
2. Animate out
3. Animate in
![image](https://user-images.githubusercontent.com/7850794/39671253-3efc3cbe-510c-11e8-8b50-8510f4c775cc.png)

**Comment by aholachek** [comment]
Hi, thank you for making an issue for this. 

After playing around with the example a few more times I realized that the issue only happens if I don't wait 4 seconds or so before toggling the "in" state after toggling the "out" state. If I wait enough after the exit animation, the "enter" state always looks good. So I think it might something with the exit animation not fully completing and holding on to old data.

**Comment by Andarist** [comment]
So I've debugged this issue and can describe what exactly happens here, hopefully we'll be able to figure out how to fix this. 

The issue happens for nested `<Transition/>` (aka `<PoseGroup/>`. Let's assume an example with smaller amount of inner items for clarity.

1. we enter `<PoseGroup><Grid><PoseGroup><Item id="1" /><PoseGroup/><PoseGroup/>`
2. we add a new item, resulting in `<PoseGroup><Grid><PoseGroup><Item id="1" /><Item id="2" /><PoseGroup/><PoseGroup/>`
3. we trigger the exit animation of the `<Grid/>`, this propagates through the "pose tree" to the Items, but React's tree has no knowledge of that, the inner `<PoseGroup/>` havent been triggered with `getDerivedStateFromProps` hook, thus its internal state hasnt changed. At this point:
- we aim for `<PoseGroup/>`
- but React still sees `<PoseGroup><Grid><PoseGroup><Item id="1" /><Item id="2" /><PoseGroup/><PoseGroup/>`
4. **during** exit animation we trigger enter animation BUT we aim for `<PoseGroup><Grid><PoseGroup><Item id="1" /><PoseGroup/><PoseGroup/>` (notice no `<Item id="2" />`). Inner `<PoseGroup/>`'s `getDerivedStateFromProps` gets triggered now, it recognizes that second `<Item/>` has been removed, so it thinks that it should transition to exit state - it tries to start the "direct" exit pose now (although it kinda already is exiting)
5. immediately `<Grid/>` starts to enter - it calls `startChildAnimations`, with `enter` pose ofc - so it cancels just set exit pose/actions/reactions/etc on 2nd Item and animates it to enter state instead (thus leaving it as DOM orphan), because exit pose gets cancelled entirely, `onPoseComplete` has no chance to get called so no `scheduleForRemoval` is called either

The whole thing also exposes a second problem - memory leaks (at least I think they are there). Things like `onPoseComplete` are dependant on Promises which depend on **cancellable** sources, such as Actions. The cancellation is swallowed from Promises stand of view and thus they stay in pending state, causing memory leaks. I would advise to stay out of using Promises for any kind of communication if cancellation is possible in the system.

**Comment by nkov** [comment]
Not sure if this is related but we were having some issues with DOM elements remaining in the `<PoseGroup>` even after they should be unmounted and turns out the key for the children was undefined sometimes, which was complained about in console. 

https://github.com/Popmotion/popmotion/issues/535 Solved by using a more stable key.

**Comment by Andarist** [comment]
This rather shouldnt be related as in this issue keys are stable and the issue still occurs.

**Comment by Andarist** [comment]
@InventingWithMonster any comments on this? I could maybe work on fixing the issue, but needs some guidance.

**Comment by Andarist** [comment]
@sarneeh thanks for offering to help, but beside actually fixing this issue Im not sure what else can be done here

@InventingWithMonster could you take a look at this? the scope of this issue is too big for me to handle on my own without guidelines how to do so because it's imho quite an architectural thing and I'm not yet that well versed in that

**Comment by Andarist** [comment]
I'll try to look into fixing this as soon as I can, but as mentioned - this might be over my head as I don't yet grasp the architecture of the pose chains in full. I understand how they work but I'm not sure how to properly fix edge cases like this - because it's not directly pose related (or maybe it is?), it has no notion of transitions, react does and it hacks a little bit into pose flow to achieve its goals (at least from what I remember about the implementation). So either we need to bookkeep some extra state in react and handle this case or move transition logic to pose core and just let react reuse it.

I'll try figure out what it would take to fix this and what kind of information is missing and where in order to handle this case properly.

**Comment by ryanwiemer** [comment]
Thanks @Andarist for looking into this issue. I really appreciate it. 

I understand that this edge case may open up bigger architecture questions. I'm hoping that since we can replicate the issue as well as have an idea of the probable cause that we can work towards a solution. 

By the way I love this open source work. It's amazing! I'm always telling people to use Popmotion. 😀
