### ISSUE TITLE
Reaction while doesn't work?

### ISSUE THREAD

**Issue by CGamesPlay** [Popmotion/popmotion#357]
I have a `value` reaction that I've called `springTo().start` on. One of the subscribers of the reaction is a `styler.set` that adjusts the position, and this is working fine.

I call `reaction.while` to create a new reaction that will complete based on some predicate. The predicate is never called and the derived reaction does not ever complete.

Am I doing something wrong, or is this a bug? Here's a CodePen with a reproduction: https://codepen.io/cgamesplay/pen/jKbJJe?editors=0010

Expected behavior: "checking the condition" is printed to the console at least once.
Actual behavior: it's not.

Using https://unpkg.com/popmotion@8.2.3/dist/popmotion.js

Am I doing it wrong, or is this a bug?

**Comment by InventingWithMonster** [comment]
There is a bug, thanks for pointing this out

**Comment by Andarist** [comment]
@InventingWithMonster Have u considered using some existing FRP solution? I would expect using one would solve those kind of cases automatically because you wouldn't have to focus on matching functional parity with them, they would just handle this for you. Considering bundle size constraints I would propose using callbags as the underlaying FRP engine. It's kinda DIY solution anyway (I could help with migrating to it), but they already have numerous operators (and all of them are lightweight) that could be just reused here.

The problem here from my quick debug session is that when creating a new reaction the data source is not shared, `applyMiddleware` etc are just copying the source "config" (props & middlewares) and creating a completely new reaction from it - so actually they do not form any kind of chain (which would solve the issue)

**Comment by Andarist** [comment]
> It might just be a messaging problem but I think the problem with being too "clever" with the API is that it permeates the whole docs and its ended up with Pure (fairly) having the reputation for being complicated.

Well, this is fair concern - for instance I'm familiar with streams in general, but how actions & reactions are interacting with each other is still a little bit blurry for me.

> I might look into callbags at some point but I'm probably more likely to look into simplifying the API and cutting down on filesize.

Sure, if you still want to have a reactive core the callbags might be a good pick - they are completely modular, there is no actual library - just operators.

> I think the fundamental problem is that Reactions are passive and I don't think they can be instrinsically "stopped" as such.

Not sure if that was the problem here - the reaction itself was not supposed to be stopped, @CGamesPlay just wanted to listen to the passively emitted events & do smth once the condition would be met.

Do you still think this should be fixed for now? Or are you planning on refactoring the API and it would be better not to touch this for now until things settle down?

**Comment by InventingWithMonster** [comment]
Closing this as moving away from reactive model

**Comment by lennerd** [comment]
What do you mean with "moving away from reactive model"? Any more infos on this? What is the plan for the future?
