### ISSUE TITLE
0 velocity

### ISSUE THREAD

**Issue by timm-aym** [Popmotion/popmotion#375]
**Describe the bug**
I have a `value` tracking the `clientX` coordinate of a touch (`touchStart`, `touchMove`).

About half of the time it returns a `0` velocity.

**To Reproduce**
Attach `touchStart`, `touchMove`, and `touchEnd` handlers to a `div`.

Instantiate a `value` in `touchStart`, call `update` in `touchMove`, and print `getVelocity` in `touchEnd`.

**Expected behavior**
For moving swipes that don't rest on the screen in the end, the `velocity` should always be non-zero.

But, as you can see, sometimes a `0` value is returned (even though the inputs look similar):

![screen shot 2018-06-13 at 15 16 38](https://user-images.githubusercontent.com/39257483/41353550-cc49598e-6f1c-11e8-91b8-8a9fd9bd98b3.png)

**Link to CodePen or similar**

(no sample extracted yet. Not sure if I am using the `value` API correctly)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Chrome on Android

**Comment by timm-aym** [comment]
I just found the "Using velocity" section on https://popmotion.io/learn/velocity-and-physics/.

There the interaction works beautifully.

When I adapted my code to not manually call `update`, but rather use `listen` like in the example at https://codepen.io/popmotion/pen/RjBZoe I always get values for the velocity.

Is that to be expected, or would you still be interested in the previous failing code / do you have an explanation why one works and the other doesn't?

Thanks!

**Comment by InventingWithMonster** [comment]
Yeah this is expected. If you use the `pointer` action to track touch input you shouldn't have this issue. 

The reason being, pointer input isn't necessarily being fired every frame, or maybe it's being fired more than once per frame.

For instance it might be true that the previous value is `200` and the next value is `201`, but it might also be true that there's been multiple frames of no movement since `201`. So `value` schedules a check at the end of the following frame. If there's been no update in the `update` part of the render loop (https://popmotion.io/api/framesync/) then it'll consider the velocity to be `0`
