### ISSUE TITLE
Keys on pose config need to be unique when nesting animations?

### ISSUE THREAD

**Issue by k90armstrong** [Popmotion/popmotion#537]
I am new to using this library and really love it! This might be a bug, or maybe I am just doing something wrong,  but it seems like when nesting posed animation components and using the same keys for the poses on both the parent and the child causes an issue when first mounting. 

here is a simplified example of what I am seeing:
https://codesandbox.io/s/q9176v0lv4

See the comments in the example for some more explanation.

Let me know if there are questions to this example. Thanks!!

**Comment by Andarist** [comment]
I'm not a pose expert - but I think that's because posed elements creates a "chain" with React's context help. This allows for orchestrating animations involving also child elements - like described [here](https://popmotion.io/pose/learn/animating-children/).

If you want to "break" the chain (use same pose keys) u might want to use `withParent={false}` prop on your `<Fade/>` component.

That being said - this could be validated by the pose in dev mode to warn people about misusing same pose keys. Not sure though at the moment if that can be easily added right now or if that would require some changes (not sure if child knows about all possible poses in the ancestor chain). WDYT @InventingWithMonster ?

**Comment by InventingWithMonster** [comment]
`show` in `Slide` is `true` so it's being set to "opened".

If you remove this logic, or fix it, it works as *I think* is expected. It's as I'd personally expect it to work at least?

**Comment by Andarist** [comment]
The `Slide` part is OK, but I think @k90armstrong was asking more about the `Fade` which is set to closed initially, but it ends up in opened state (because of its parent - Slide - being in opened pose).

**Comment by InventingWithMonster** [comment]
Ahhh I see. Yeah that might be a fair fix, though as you point out there is already a prop to control this and I wonder how complex that might end up being to implement.

@k90armstrong can you confirm adding `withParent={false}` to `Fade`'s `this.Animator` fixes your problem?

**Comment by Andarist** [comment]
I think I've tested it yesterday - and it did the trick. I'll try to explore in free time to see what it woudl take to validate this stuff in dev mode.

**Comment by k90armstrong** [comment]
yes the `withParent={false}` prop works just how i need it to.  Thanks for the help!
