### ISSUE TITLE
react-pose: parent / child poses: parent-pose is "winning" from child pose

### ISSUE THREAD

**Issue by klaasman** [Popmotion/popmotion#545]
See this codesandbox: https://codesandbox.io/s/n4y8r9o7pp

I would expect child pose definitions to extend parent pose definitions, though it seems to be the other way around. Is someone able to explain to me why it's working like this? Am I missing something?

```jsx
const Parent = posed.div();
const Child = posed.div({
  green: {
    background: "rgba(0, 255, 0, 1)"
  },
  red: {
    background: "rgba(255, 0, 0, 1)"
  }
});

function Example() {
  return (
    <React.Fragment>
      <Child className="child" pose="red">
        I'm `red`, as expected
      </Child>

      <Parent pose="green">
        <Child className="child" pose="red">
          my parent-pose is `green`, my own pose is `red`.
          <br/>
          I'd expect me to be `red`, though I'm `green`.
        </Child>
      </Parent>
    </React.Fragment>
  );
}
```

![image](https://user-images.githubusercontent.com/85814/46607091-eeff9a80-caff-11e8-8b4a-7c7078dea2db.png)

**Comment by Andarist** [comment]
I have no idea how this **should** behave, need to give it more thought - are there any example in the docs how composing poses work? Can't recall any now - most examples I remember uses a single or bunch of posed elements, but use pose props only on a single one and let it flow through the tree,

The issue is caused by automatic pose propagation through posed elements - looking into the source you can see why exactly this happens:
https://github.com/Popmotion/popmotion/blob/879e6f0300933947fd6de8ef24403697460a2934/packages/react-pose/src/components/PoseElement/index.tsx#L91

You do not specify `initialPose` so `getInitialPoseFromParent` gets called and that's how your element ends up being green, other issue is that the return value of your `getInitialPose` there is `['green', 'red']` so it seems that first items have higher priority when it comes to conflicting rules (backgroundColor in your case), maybe it should be the other way around?
