### ISSUE TITLE
[discussion] Should onPoseComplete fire for nested elements?

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#548]
Issue explained in more detail - https://github.com/Popmotion/popmotion/issues/544#issuecomment-427795361

Example - https://codesandbox.io/s/xzxk44jrww .

I'm not sure how exactly this could be utilized, but it seems reasonable that people might expect this callback being fired for nested elements.

**Comment by nkov** [comment]
I believe it should. It makes semantically, that any element which is animating should have the callback fired when it's relevant. For me, the use case is like this:

I am using `react-router` to navigate and I have a child component which animates on the mount. From this discussion, I learned that the `onPoseComplete` event fires on the parent, but I need it to fire in this component so that I can change the local state. The new component which loads has an input box, which slides up from the bottom when the component mounts. This all works great. However I need the `<input>` to be disabled until the the animation is complete (to fix a quick with iOS). To accomplish this, I set a local state: `inputDisabled: true` and expect that `onPoseComplete` will fire when the input finishes sliding up, so that I can set `inputDisabled` to false.

**Comment by Andarist** [comment]
Makes sense to me. Would you be willing to look into implementing this?

**Comment by nkov** [comment]
I haven't written TS before but this seems like a good opportunity to get my feet wet. I can give it a try when I have some time, any pointers on where to start looking?

**Comment by Andarist** [comment]
If you remove `initialPose` then no transition happens on mount, so `onPoseComplete` doesn't fire.
