### ISSUE TITLE
 onDragStart/onDragEnd triggered by mouse down and mouse up without dragging?

### ISSUE THREAD

**Issue by yuensunn** [Popmotion/popmotion#549]
Refer to the example below. Clicking on the white box (with popmotion pose) without dragging still triggers onDragStart and onDragEnd event. The red regular div box without popmotion pose does not seem to have this problem. 

https://codesandbox.io/s/4w8z8o7k44

**Comment by emilbruckner** [comment]
It’s because elements enter drag state onMouseDown with this library. 
I guess that won’t be changed, as animations look more natural when the drag state triggers as soon as an item is picked not, not when it’s first moved.
What’s your problem with the current behaviour?

Your example also doesn’t set `draggable="true"` for the regular div by the way.

**Comment by yuensunn** [comment]
Hi. thanks for the reply. I'm trying to make a draggable parent with a list of buttons in it. However whenever I drag the parent div the children button onclick will be triggered as well. I was looking for a solution to stop propagating the click event to the children whenever the parent div is dragged.

**Comment by emilbruckner** [comment]
You could listen for the dragStart & dragEnd events and compare the values you get. If event.x & event.y don’t change, you know that nothing was dragged.

**Comment by yuensunn** [comment]
Thanks alot! I have solved the issue

**Comment by emilbruckner** [comment]
You could make use of the dragEnd pose
