### ISSUE TITLE
Fix and/or normalize stylefire svg origin config

### ISSUE THREAD

**Issue by jasonkuhrt** [Popmotion/popmotion#573]
https://codesandbox.io/s/0yn85l382l

~https://codesandbox.io/s/l2q5q9on2q~ 

~In the above demo I am trying to animate a triangle at its center-left; note:~

* ~svg origin-x requires `-8px` but expected to be able to just set `0px`~
* ~html origin x/y config have no effect seemingly but expected to work~
* ~html origin x/y appears to default to top-left which is not the same as what the svg appears to default to: bottom-right.~
* css animated one has the origin config we presumably want to emulate not to mention that the docs already state:

> Easy SVG transforms: Replaces the complex SVG transform model with the user-friendly CSS equivalent.

see [comment below](https://github.com/Popmotion/popmotion/issues/573#issuecomment-431698501), much clearer

**Comment by InventingWithMonster** [comment]
Yeah it looks like there's a bug with origin calculations.

In this example are you intuitively expecting `originX` to be pixels or percentage?

**Comment by jasonkuhrt** [comment]
I was thinking pixels. Though come to think of it working in terms of percentage would be way nicer, at least for my use case here.

**Comment by jasonkuhrt** [comment]
I put some more work into what I think its a much better demo. Using squares and more careful/cleaner cases, we can now see:

* html popmotion transform origin works just like html css transform origin OK
* svg popmotion transform however is I think fair to call odd, and from a user POV arguably buggy... the default origin is bottom-right, setting 0,0 is alright bottom-right, however any non-0 value is movement relative to 50%,50% (!!).

link: https://codesandbox.io/s/0yn85l382l

**Comment by jasonkuhrt** [comment]
Updated the squares demo to 75px squares so that its clear the movements are percentage and not px (e.g. -50 for a 100px square is ambiguous if its necessarily px of %).

**Comment by InventingWithMonster** [comment]
Thanks, I've built a local sandbox for the repo though I won't get a chance to look at the code until after React Conf

![image](https://user-images.githubusercontent.com/7850794/47296091-2b0b2300-d609-11e8-85ae-8566c6422408.png)

**Comment by danielpaull** [comment]
I thought I'd chime in on this because I think that this normalisation is a really bad idea without a way to alternatively use the SVG transformation directly.

In my case, I'm building a mapping application and have various entities drawn on the map in SVG.  The utmost in care has been taken to ensure that the drawings are accurate down to the millimeter.  This is achieved by setting up the svg element size and view box to establish a local coordinate system in which drawing can be done with the correct scale, orientation and location.  We are using Vue (and so vue-pose) to animate the SVG elements when they are data-driven, and this leads us to a number of problems with the current handling of transformations:

1. We can not use percentages.  Drawing is to be done in the units set up by the view box.

2. Or view box already sets up an origin and that needs to be honoured by our SVG components, so the coordinate system used to specify coordinates should not be altered.

3. The drawing scale must not be changed.

One of the biggest problems we face with the current implementation is the use of SVGGraphicsElement.getBBox() to determine the size of the drawing.  Firstly, this is meaningless in our setting - if we were to use percentages, it would be a percent of the viewBox or SVG element size, not a percentage of the size of the children of the element being animated.  But further to this, if the drawing is at all dynamic (eg, animated parts or parts being added/removed over time, say with v-if directives in Vue) then this bounding box may vary over time and cause inconsistencies.  As an example, I was drawing a truck that has an animated part the extends out the side of the truck by 1m.  When stylefire calls getBBox(), the width of the truck drawing depends on the whether that part is extended, which depends on application state.  This means that a rotation centre specified as a percentage of the width of the bounding box will change depending on the application state at the time the SVG was created.  The result being that some trucks draw correctly and other that don't.  To address this I would have to call getBBox() myself to be able to calculate percentages consistently, but I can not guarantee that the bounding box I get will be the same as what Stylefire used because the bounding box is time varying.

I would urge you to include SVG specific properties (eg, svgCentreX, svgCentreY, etc) for those who are not only comfortable with the "complex SVG transform model", but need to use it because of how it interacts with SVG element sizing and viewbox definitions.  An alternative would be to include a property to indicate if the transformation should use the SVG or CSS convention.

For anyone else facing this issue, my current workaround is to add a transparent rectangle to my drawing that matches the viewBox size to trick the getBBox() call, but this is not an acceptable solution.

Otherwise, popmotion is working well for us :)  Thanks!

**Comment by danielpaull** [comment]
To me the whole point of using vue-pose was to avoid creating transform strings.  I'm not even sure how you'd do that with vue-pose as I don't think it's a supported values for animation - can you give an example of how?

Relevant documentation: https://popmotion.io/pose/api/supported-values/#supported-values-css-transforms
