### ISSUE TITLE
Animations with a delay are stuttering during scroll (chrome only)

### ISSUE THREAD

**Issue by klaasman** [Popmotion/popmotion#643]
Have a look at [this screen-record](https://github.com/Popmotion/popmotion/files/2604008/Screen.Recording.2018-11-21.at.11.04.49.mov.zip) (zipped because github doesn't accept *.mov-files).
The expected behavior can be seen in this codesandbox: https://codesandbox.io/s/4jzzvm1vz7.

I noticed this weird glitch when I was firing an animation at the moment when someone scrolled some element into the viewport. The animations consisted of staggered children, but these children weren't waiting correctly for eachother, they appeared in "groups".  
Initially I thought it might had something to do with other code (.e.g. scroll listeners), but after eliminating everything except the animation itself, it was still stuttering.

One thing I didn't expect is that it's only happening on Chrome. Both Safari as Firefox are doing an excellent job.

Any idea what is causing this? Or how to fix it?

**Comment by Andarist** [comment]
I have looked at this quickly and I've noticed that some rAFs are being delayed (maybe because other work happening on a main thread).

However I can't reproduce this when recording with profiler - so maybe this is just some Chrome (in non-profiler mode 🤦‍♂️ ) bug? I've only checked it on codesandbox which is doing some work on its own - although it didnt show up as significant in the profiler anyway. Have you reproduced this in standalone build too? Is it causing you problems in real world app?

Side note - I've also confirmed that there any no event listeners on the page by running:
```js
[...document.querySelectorAll('*')].map(el => getEventListeners(el))
```

**Comment by klaasman** [comment]
So .. I found out it's only happening when there's an external monitor attached to my macbook 🤷‍♂️  
I'm sure it's not easy to fix this issue and it's not worth the investment to fix an issue which is happening only when both in chrome and have an external display attached.

I'll close it, thanks for your time though :-)

**Comment by klaasman** [comment]
Oh and, for whatever it's worth it, I do might be able to record the issue with the profiler. Would you still be interested in an export?

**Comment by Andarist** [comment]
Hm, yeah - sure. Although it seems that it might not help (as this issue is weird) but I could definitely take a look!

I have also seen this effect (to some extent) without having external monitor plugged in.
