### ISSUE TITLE
[react-pose] Scaled text is blurry in demos

### ISSUE THREAD

**Issue by amcdnl** [Popmotion/popmotion#660]
## Issue
On the demo page, if you look carefully at the interactive example when you hover you will notice the text is blurry.

![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/25fda2f3-9dd6-4b6e-b7ad-c8c7eafa62b1/2018-12-05_07-23-06.png)

This seems like a pretty common issue when doing transforms. Some people suggested setting the `perspective` property on the transform ( https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome ) but thats not possible given the component is overriding the transform.

Any suggestions/ideas?

**Comment by InventingWithMonster** [comment]
I think perspective would still bring up this issue because the reason
these animations are performant is the element has already been rendered
and sent to the GPU as a raster image.

The only way around it (this applies to CSS too) is to render at a higher
resolution and scale down. In other words make the element larger to begin
with and then set scale: 0.9 (for instance) as the smaller scale and scale:
1 as the larger scale

**Comment by amcdnl** [comment]
Gotcha - Thanks for the info - Closing.

**Comment by amcdnl** [comment]
@InventingWithMonster - If you do `will-change: transform;` it removes the blur! :) - Might want to consider applying that automatically?

**Comment by Aleksion** [comment]
@InventingWithMonster this also happens on react native. Performance is phenomenal when I use x or y to animate, but all text in the animated container becomes blurry as a result of it:

```typescript
{
	slideUp: (end: number = 0, start: number = -500) => ({
		[Animations.Shown]: {
			y: end,
			transition: {
				delay: 50,
				duration: 350,
				useNativeDriver: true,
			},
		},
		[Animations.Hidden]: {
			y: start,
			transition: {
				delay: 50,
				duration: 350,
				useNativeDriver: true,
			},
		},
	})
	}

```

**Comment by twillstudio** [comment]
Hi guys, I am facing a similar issue on react-native-pose. i am using Transitions in order to slide booking components one by one. Here is a short part of my code for you to understand better what i'm doing.

```
<Transition
    enterBookingFlow={this.state.enterBookingFlow}
    deltaIVProduct={this.state.widthSlideIVProduct} 
    deltaLocation={this.state.widthSlideLocation} 
    deltaTime={this.state.widthSlideTime}
    >
<BoxListProduct/>
{
          this.props.dataFlow.currentPage == 'Time'?
       <BoxTime
         key="d"
         onRef={ref => (this.timePicker = ref)}
         pose={this.state.showBookingFlow && this.props.dataFlow.currentPage == 'Time'? 'enter' : 'exit'}
         next={this.next.bind(this)}
         backTime={this.backTime.bind(this)}
        />
        :null
       }
</Transition>
```

And here is the result on my Time component, the native IOS picker is blurred and it looks like it is because of the transition component. Do you have any idea on how to fix it ?
![Simulator Screen Shot - iPhone X - 2019-04-07 at 12 14 49](https://user-images.githubusercontent.com/36391774/55677637-c893ae00-592e-11e9-98d7-9f39d6e45dfd.png)

Thanks very much in advance!
