### ISSUE TITLE
[react-pose] Calling setState() during PoseGroup transition causes entering component to lose current animation

### ISSUE THREAD

**Issue by msheakoski** [Popmotion/popmotion#684]
Calling setState() during a PoseGroup transition causes the component that is entering to ignore the enter pose's transition configuration. In my CodeSandbox example, "2" should slide in with linear easing for 3 seconds, but when setState() is called 1 second into the animation, it seems to revert to the automatically generated Movement/spring animation instead.

## How to reproduce
1. View the CodeSandbox example
2. Click on the "1" box to start the transition
3. Observe that after 1 second, "2" slides in very fast instead of maintaining the current three second linear animation

## Affected versions
4.0.2 - 4.0.5
Also interesting, when I switch to 4.0.1, the animation seems to slow down instead of speed up like in later versions.

## Expected behaviour
The component entering ("2" in the example) should maintain the configured animation instead of switching to the automatically generated animation

## Link to CodePen example (or similar)
[![Edit l48wl5jno9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l48wl5jno9)

## Device information
In which environment are you reproducing the bug?
 - OS: macOS 10.14
 - Browser: Chrome / Safari
 - Version: 71 / 12

## Additional context
Am I going about this transition correctly or is there a better way that I should be doing it?

**Comment by arv433** [comment]
Same problem here, any solutions?

**Comment by Andarist** [comment]
I'm investigating this - could you confirm that 4.0.1 behaviour (slowing down) should be also considered incorrect?

**Comment by Andarist** [comment]
@esquevin your PR ( https://github.com/Popmotion/popmotion/pull/683 ) has changed behaviour in this case. Not saying that's bad or anything. I believe this particular case was not working properly either before your change nor after it.

**What's the core of this issue?**
Rerendering during animation.

**Is this particular rerendering supposed to influence the animation?**
No.

**Why does it influence it then?**
Because `handleTransition` assumes the elements are `moving` when rerendering in the middle of the animation. And because `moving` elements receive new pose - which is `['enter', 'flip']`.

**How @esquevin PR influenced the behaviour here?**
It has changed what is being considered to be `moving` - https://github.com/Popmotion/popmotion/pull/683/files#diff-271a19754681b0fded5f3976a5f22117L98 

**How this could be fixed?**
Not sure, `flip` pose is working kinda magically and I dont quite grasp how it is supposed to work. Because it's an additional pose which gets injected implicitly it changes the animation while its playing even if its not supposed to - its defaults affect `enter` (and probably `exit` too) poses.

**Comment by msheakoski** [comment]
> I'm investigating this - could you confirm that 4.0.1 behaviour (slowing down) should be also considered incorrect?

I would consider that to be incorrect as well. From a DX perspective, I feel that an animation should only change in the middle of playback if something explicitly interrupts it, such as setting a new pose or responding to input.
