### ISSUE TITLE
react-pose: global reuse of popmotion in 4.0.5

### ISSUE THREAD

**Issue by sgilligan** [Popmotion/popmotion#705]
I hope I'm not missing something, but I can't seem to use a global instance of popmotion from react-pose 4.0.5

to reproduce the behaviour:
1. Go to this codepen: https://s.codepen.io/sgilligan/debug/wNvWJw/XBAGRZQEbayr which references popmotion, react-pose and react via the global scripts of:
```
https://cdn.jsdelivr.net/npm/react@16.7.0/umd/react.development.js
https://cdn.jsdelivr.net/npm/popmotion@8.6.0/dist/popmotion.global.min.js
https://cdn.jsdelivr.net/npm/react-pose@4.0.5/dist/react-pose.dev.js
```

2. refresh with the console open and observe the javascript console error 
TypeError: popmotion is null

Tested in current versions, chrome/firefox, macos.

**Comment by InventingWithMonster** [comment]
I'm actually getting this error with your link :

![image](https://user-images.githubusercontent.com/7850794/51525561-81fedf00-1e28-11e9-8339-6aadf57ca89a.png)

**Comment by Andarist** [comment]
This is weird because according to https://cdn.jsdelivr.net/npm/react-pose@4.0.5/dist/react-pose.dev.js the UMD wrapper has such arguments:
```js
}(this, (function (exports,popmotion,React) { 'use strict';
```
which gets called with
```js
    (factory((global.pose = {}),null,global.React));
```
So `null` gets assigned to popmotion inside the UMD closure.

However this output file got somehow corrupted (?) - if we build it locally we can see that it should only try to reuse `React`:
```js
    (factory((global.pose = {}),global.React));
}(this, (function (exports,React) { 'use strict';
```
`popmotion` is not specified as `external` for that build:
https://github.com/Popmotion/popmotion/blob/7c7ed32a35a695b3779f9b4f16329969ddd6e16b/packages/react-pose/rollup.config.js#L44
So I'm not sure wha has happened - the solution would be to rebuild the package, ensure this file looks good and publish new patch version with it.

Also - unpkg has the same file cached: https://unpkg.com/react-pose@4.0.5/dist/react-pose.dev.js so its probably also published just like this to npm, maybe something is wrong on your machine @InventingWithMonster ? Because "fresh" 4.0.6 is also broken in the same way 🤔

**Comment by sgilligan** [comment]
Sorry about that codepen behaviour, not sure what is going on there. This should work: [https://codepen.io/sgilligan/full/wNvWJw](https://codepen.io/sgilligan/full/wNvWJwl)

**Comment by rafaelderolez** [comment]
Can confirm, I'm experiencing the same issue on this [Codepen](https://codepen.io/rafaelderolez/pen/JxddGg?editors=0010).

**Comment by sgilligan** [comment]
will close this as 4.0.7 (https://unpkg.com/react-pose@4.0.7/dist/react-pose.dev.js) has fixed the UMD wrapper
