### ISSUE TITLE
What is the real size of the lib?

### ISSUE THREAD

**Issue by rafaellyra** [Popmotion/popmotion#73]
The repository description says:
`A 14kb Javascript motion engine. Use for animation, physics and input tracking.`

The readme says:
`Popmotion is a 12kb JavaScript motion engine. Use it for for animation, physics, and input tracking. In the browser, on Node, anywhere.`

And the downloaded file have: `39.145 bytes (41 KB on disk)`

I think is good to unify this and also clarify if this size is when `gziped` and `minified`.

**Comment by InventingWithMonster** [comment]
Hey man, fixed the repo - it should read 12kb. A couple days ago I realised I was measuring it wrong and tried to change most references to this.

Framework sizes are usually stated as gzipped, so that's what we've done here too. Minified is 41kbish as you say, and non-minified is roughly 10x that off the top of my head.
