### ISSUE TITLE
Popmotion: Can't make css perspective work

### ISSUE THREAD

**Issue by b00sta** [Popmotion/popmotion#738]
## Describe the bug
Visually, perspective isn't applied to element.

## Expected behaviour
Perspective should be applied.

## Link to CodePen example (or similar)
https://codesandbox.io/s/q37ww2o9qq

**Comment by sjaq** [comment]
Ran into exactly the same issue. The problem seems to be that perspective is applied as a direct css style and not as a transform style.

### Expected applied style
```css
transform: perspective(600px);
```

### Actual applied style
```css
perspective: 600px;
```

I've tried to look for a way to bypass this but can't seem to find a way to override the generated transform string either so this completely breaks animations that depend on the `perspective()` transform.

**Comment by sjaq** [comment]
Spent some time investigating the cause of this issue and there seems to be a mismatch in the `transform-props.ts` and `value-types.ts` files for the css setup in stylefire.

Changing [this line](https://github.com/Popmotion/popmotion/blob/master/packages/stylefire/src/css/transform-props.ts#L4 ) to use 'perspective' instead of 'transformPerspective' fixes the issue for me in stylefire. But not sure if this is actually the right way to fix it.

**Comment by InventingWithMonster** [comment]
`transformPerspective` is the correct property to use indeed, as `perspective` is an actual CSS prop too.
